<?php
function upload_images_init(){
	return ;
}

function upload_images_permission() {
	return array(
		'administer upload_images' => array(
			'title' => t('Administer Image Upload module'),
			'description' => t('Administrating tasks for Upload Images module'),
		),
	);
}

function upload_images_menu() {
	$items['admin/config/upload_images'] = array(
		'title' => 'Upload Images',
		'description' => 'Upload Images configuration',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('upload_images_admin_settings'),
		'access arguments' => array('administer upload_images'),
		'file' => 'upload_images.admin.inc',
		'file_path' => drupal_get_path('module','upload_images')
	);
	$items['admin/config/upload_images/default'] = array(
		'title' => 'Path',
		'type' => MENU_DEFAULT_LOCAL_TASK,
		'weight' => -1,
	);
	$items['admin/config/upload_images/node'] = array(
		'title' => 'Create',
		'page callback' => 'upload_images_page',
		'access arguments' => array('access content'),
		'type' => MENU_LOCAL_TASK,
		'file' => 'upload_images.page.inc',
		'file_path' => drupal_get_path('module','upload_images'),
		'weight' => 1,
	);
	return $items;
}

function upload_images_form_alter(&$form, &$form_state, $form_id) {
	switch ($form_id) {
		case 'edit_submit':
			$form['submit']['submit']['#value'] = 'works';
			break;

		default:
			# code...
			break;
	}
	return;
}
